FROM ghcr.io/openconext/openconext-basecontainers/php82-apache2:latest
# Set the default workdir
WORKDIR /var/www/html
ADD output.tar /var/www/html/
# Add the application configuration files
COPY config/openconext/parameters.yaml.dist config/openconext/parameters.yaml
COPY .env.docker .env

# Add the config files for Apache2
RUN rm -rf /etc/apache2/sites-enabled/*
COPY ./docker/conf/apache2.conf /etc/apache2/sites-enabled/apache2.conf
RUN mkdir -p /var/www/html/var && \
  rm -rf /var/www/html/var/cache/prod && \
  chown -R www-data /var/www/html/var

CMD ["apache2-foreground"]
