# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: nl

services:
    _defaults:
        autowire: true
        autoconfigure: true

    Surfnet\Gssp\Infrastructure\:
        resource: '../src/Surfnet/Gssp/Infrastructure/*'
        exclude: '../src/Surfnet/Gssp/Infrastructure/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    Surfnet\Gssp\Infrastructure\Controller\:
        resource: '../src/Surfnet/Gssp/Infrastructure/Controller/*'
        tags: ['controller.service_arguments']

when@dev:
    services:
        _defaults:
            autowire: true
            autoconfigure: true

        Dev\:
            resource: '../dev/*'
            exclude: '../dev/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

        # controllers are imported separately to make sure services can be injected
        # as action arguments even if you don't extend any base controller class
        Dev\Controller\:
            resource: '../dev/Controller'
            tags: [ 'controller.service_arguments' ]

when@test:
    services:
        _defaults:
            autowire: true
            autoconfigure: true

        Surfnet\Gssp\Test\Features\Context\WebContext:
            public: true
            arguments:
                - "@kernel"
