name: Create release and Build and Push docker production image

on:
  push:
    tags:
      - "*.*.*"

jobs:
  build-release-and-push-container:
    uses: openconext/openconext-githubactions/.github/workflows/symfony-release.yml@main
    with:
      component_name: "Stepup-gssp-example"
