name: build-push-test-docker-image

on:
  workflow_dispatch:

jobs:
  build-release-and-push-test-image:
    uses: openconext/openconext-githubactions/.github/workflows/build-push-test-docker-image.yml@main
    with:
      component_name: "Stepup-gssp-example"
      use_yarn: true
