name: Run acceptance tests (Behat)
on: [pull_request]

jobs:
  run-qa-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: /var/www/html/
    container:
      image:  ghcr.io/openconext/openconext-basecontainers/php82-apache2-node20-composer2:latest
      volumes:
        - .:/var/www/html
      options: -h gssp.stepup.example.com 

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Copy some config
        run: cp docker/conf/apache2_ssl.conf /etc/apache2/sites-enabled/ && rm /etc/apache2/sites-enabled/000-default.conf

      - name: Do a graceful restart of apache2
        run: a2enmod ssl && apachectl -k graceful

      - name: Composer install
        run: composer install
      
      - name: Run QA tests
        run: composer behat
